model: LSTM

# 数据集
data_path: "./Dataset"  # 数据集路径
#class_labels: ["angry", "fear", "happy", "neutral", "sad", "surprise"]  # 情感标签
#class_labels: ["焦虑抑郁","双相躁狂","双相障碍", "抑郁", "抑郁焦虑强迫", "正常"]
class_labels: ["yy", "jl","zc"]
# class_labels: ["zk", "no", "yy", "jl", "sx"]
# class_labels: ["angry", "boredom", "disgust", "fear", "happy", "neutral", "sad"]

# 特征存储
feature_path: features/test1/  # 特征存储路径

#train_feature_path_opensmile: features/6-category/train_opensmile_casia.csv  # 训练特征存储路径（Opensmile）
#predict_feature_path_opensmile: features/6-category/test_opensmile_casia.csv  # 预测特征存储路径（Opensmile）

train_feature_path_librosa: features/test1/train_librosa_casia.p  # 训练特征存储路径（librosa）
predict_feature_path_librosa: features/test1/predict_librosa_casia.p  # 预测特征存储路径（librosa）

# 特征提取方式
feature_method: l  # 'o': opensmile, 'l': librosa

# Opensmile 配置，只在 'feature_method: o' 时 需要设置
#opensmile_config: IS10_paraling  # Opensmile 标准特征集
#opensmile_path: /Users/zou/opensmile-2.3.0  # Opensmile 安装路径

# checkpoints
checkpoint_path: checkpoints/  # checkpoint 存储路径
checkpoint_name: checkpoint_model_acc_0.841  # checkpoint 文件名

# 训练参数
epochs: 1800  # 训练 epoch 数
batch_size: 4  # 批大小
# lr: 0.01  # 学习率
# 模型参数
rnn_size: 128  # LSTM 隐藏层大小
hidden_size: 32
dropout: 0.2
